#FOR TIMESTAMP FORMAT 05/11/2024 16:59:44 
metrics:
  apply_finish_time:
    query: "
        SELECT SOURCE_DBID, VALUE
        FROM V$DATAGUARD_STATS
        WHERE NAME='APPLY_FINISH_TIME'
        ORDER BY CAST(CONCAT(
        SUBSTRING(TIME_COMPUTED, 7, 4), '-', 
        SUBSTRING(TIME_COMPUTED, 1, 2), '-', 
        SUBSTRING(TIME_COMPUTED, 4, 2), 
        SUBSTRING(TIME_COMPUTED, 11, 9)) AS DATETIME) 
        DESC LIMIT 1;  
        " 
    type: gauge
    description: "Provides an estimate of the time remaining for the standby to finish applying all the received, but unapplied redo data from the primary database."
    labels: ["source_dbid"]
    value: "value"
    function: "to_millisec"
    
  apply_lag:
    query: "
        SELECT SOURCE_DBID, VALUE
        FROM V$DATAGUARD_STATS
        WHERE NAME='APPLY_LAG'
        ORDER BY CAST(CONCAT(
        SUBSTRING(TIME_COMPUTED, 7, 4), '-', 
        SUBSTRING(TIME_COMPUTED, 1, 2), '-', 
        SUBSTRING(TIME_COMPUTED, 4, 2), 
        SUBSTRING(TIME_COMPUTED, 11, 9)) AS DATETIME) 
        DESC LIMIT 1; 
        " 
    type: gauge
    description: "This indicates how far behind the data in the standby database is compared to the primary database."
    labels: ["source_dbid"]
    value: "value"
    function: "to_millisec"

  transport_lag:
    query: "
        SELECT SOURCE_DBID, VALUE
        FROM V$DATAGUARD_STATS
        WHERE NAME='TRANSPORT_LAG'
        ORDER BY CAST(CONCAT(
        SUBSTRING(TIME_COMPUTED, 7, 4), '-', 
        SUBSTRING(TIME_COMPUTED, 1, 2), '-', 
        SUBSTRING(TIME_COMPUTED, 4, 2), 
        SUBSTRING(TIME_COMPUTED, 11, 9)) AS DATETIME) 
        DESC LIMIT 1; 
        " 
    type: gauge
    description: "This represents the delay in transferring redo data from the primary database to the standby."
    labels: ["source_dbid"]
    value: "value"
    function: "to_millisec"

    
  dataguard_status_dataguard:
    query: "
        SELECT *
        FROM V$DATAGUARD_STATUS
        WHERE TIMESTAMP = (
        SELECT MAX(TIMESTAMP)
        FROM V$DATAGUARD_STATUS
        ) and FACILITY = 'Data Guard';
        "
    type: info
    description: "dataguard status log"
    labels: ["facility", "severity", "message"]
    value: ""
    function: ""
    
    
  dataguard_status_log_transport:
    query: "
        SELECT *
        FROM V$DATAGUARD_STATUS
        WHERE TIMESTAMP = (
        SELECT MAX(TIMESTAMP)
        FROM V$DATAGUARD_STATUS
        ) and FACILITY = 'Log Transport Services';
        "
    type: info
    description: "log transport services"
    labels: ["facility", "severity", "message"]
    value: ""
    function: ""
    


  dataguard_status_log_apply_services:
    query: "
        SELECT *
        FROM V$DATAGUARD_STATUS
        WHERE TIMESTAMP = (
        SELECT MAX(TIMESTAMP)
        FROM V$DATAGUARD_STATUS
        ) and FACILITY = 'Log Apply Services';
        "
    type: info
    description: "log apply services"
    labels: ["facility", "severity", "message"]
    value: ""
    function: ""



  dataguard_status_role_management_services:
    query: "
        SELECT *
        FROM V$DATAGUARD_STATUS
        WHERE TIMESTAMP = (
        SELECT MAX(TIMESTAMP)
        FROM V$DATAGUARD_STATUS
        ) and FACILITY = 'Role Management Services';
        "
    type: info
    description: "role management services"
    labels: ["facility", "severity", "message"]
    value: ""
    function: ""


  

  dataguard_status_remote_file_server:
    query: "
        SELECT *
        FROM V$DATAGUARD_STATUS
        WHERE TIMESTAMP = (
        SELECT MAX(TIMESTAMP)
        FROM V$DATAGUARD_STATUS
        ) and FACILITY = 'Remote File Server';
        "
    type: info
    description: "remote file server"
    labels: ["facility", "severity", "message"]
    value: ""
    function: ""




  dataguard_status_fetch_archive_log:
    query: "
        SELECT *
        FROM V$DATAGUARD_STATUS
        WHERE TIMESTAMP = (
        SELECT MAX(TIMESTAMP)
        FROM V$DATAGUARD_STATUS
        ) and FACILITY = 'Fetch Archive Log';
        "
    type: info
    description: "fetch archive log"
    labels: ["facility", "severity", "message"]
    value: ""
    function: ""



  
  dataguard_status_crash_recovery:
    query: "
        SELECT *
        FROM V$DATAGUARD_STATUS
        WHERE TIMESTAMP = (
        SELECT MAX(TIMESTAMP)
        FROM V$DATAGUARD_STATUS
        ) and FACILITY = 'Crash Recovery';
        "
    type: info
    description: "crash recovery"
    labels: ["facility", "severity", "message"]
    value: ""
    function: ""



  dataguard_status_network_services:
    query: "
        SELECT *
        FROM V$DATAGUARD_STATUS
        WHERE TIMESTAMP = (
        SELECT MAX(TIMESTAMP)
        FROM V$DATAGUARD_STATUS
        ) and FACILITY = 'Network Services';
        "
    type: info
    description: "network services"
    labels: ["facility", "severity", "message"]
    value: ""
    function: ""


